import type { IconThemeDocument } from './iconThemeCss';
import { escapeForCssClass } from './cssEscape';

export interface FileIconClassesOptions {
  name: string;
  isDirectory?: boolean;
  isRoot?: boolean;
  theme: IconThemeDocument;
}

/**
 * Generates CSS class names for file/folder icon rendering.
 *
 * The returned classes match selectors generated by `generateIconThemeCss()`
 * and follow the same pattern as VS Code's `getIconClasses()`.
 */
export function getFileIconClasses({
  name,
  isDirectory,
  isRoot,
  theme,
}: FileIconClassesOptions): string[] {
  if (isDirectory) {
    const classes = isRoot ? ['rootfolder-icon'] : ['folder-icon'];
    const lower = name.toLowerCase();

    // Folder name matching
    if (theme.folderNames && lower in theme.folderNames) {
      classes.push(`${lower}-name-folder-icon`);
    }
    classes.push('name-folder-icon');

    return classes;
  }

  // ---- File ----
  const classes: string[] = ['file-icon'];
  const lower = name.toLowerCase();

  // Extension-based classes — generate suffix combinations like VS Code's
  // getIconClasses(). For dotfiles (names starting with "."), also check each
  // individual segment, since suffixes like "env.example" won't match "env"
  // in the theme even though the file is clearly an env variant.
  const parts = lower.split('.');
  const isDotfile = lower.startsWith('.');
  if (parts.length > 1 && theme.fileExtensions) {
    const extMap = theme.fileExtensions;

    // Suffix combinations (exact VS Code behaviour): "env.example", "example"
    for (let i = 1; i < parts.length; i++) {
      const suffix = parts.slice(i).join('.');
      if (suffix in extMap) {
        classes.push(`${suffix}-ext-file-icon`);
      }
    }

    // Dotfile heuristic — for .env.example / .env.local / .gitignore.local
    // the meaningful extension is the first segment after the leading dot.
    if (isDotfile) {
      const alreadyMatched = new Set(
        classes.filter(c => c.endsWith('-ext-file-icon'))
      );
      for (let i = 1; i < parts.length; i++) {
        const seg = parts[i];
        if (seg && seg in extMap) {
          const cls = `${seg}-ext-file-icon`;
          if (!alreadyMatched.has(cls)) {
            classes.push(cls);
          }
        }
      }
    }

    classes.push('ext-file-icon');
  }

  // Filename-based class (for name-file-icon)
  const baseName = parts[0];
  if (baseName) {
    classes.push(`${baseName}-name-file-icon`);
  }
  classes.push('name-file-icon');

  // Specific filename matching (placed AFTER generic name/extension classes
  // so the CSS source-order priority can apply)
  if (theme.fileNames) {
    if (lower in theme.fileNames) {
      classes.push(`${lower}-name-file-icon`);
    }
    // Also check lowercased matching for case-insensitive filesystems
    if (lower !== name && name in theme.fileNames) {
      classes.push(`${escapeForCssClass(name)}-name-file-icon`);
    }
  }

  return classes;
}
